apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: time-job-every-fifteen-minutes
spec:
  schedule: "0,15,30,45 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: time-batch-job
        spec:
          restartPolicy: OnFailure
          containers:
          - name: main
            image:  agustinfiorenza/time-job
