apiVersion: v1
kind: Pod
metadata:
  name: backend
spec:
  containers:
  - image: agustinfiorenza/backend
    name: backend
    imagePullPolicy: Always
    ports:
    - containerPort: 3000
      protocol: TCP
    livenessProbe:
      httpGet:
        path: /healthz
        port: 3000
      initialDelaySeconds: 15
      timeoutSeconds: 1
