apiVersion: v1
kind: ReplicationController
metadata:
  name: backend
spec:
  replicas: 3
  selector:
    app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: agustinfiorenza/backend
        ports:
        - containerPort: 8080
